services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ssd/appdata/homebridge:/homebridge
    environment:
      - PUID=3010
      - PGID=3010
      - TZ=America/Los_Angeles
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
